version: '3.3'
services:
 backend:
   image: dto80/234-lab11:latest
   ports:
    - "8085:8080"
   volume:
    - type: bind
      source: ./data
      target: /data
 frontend:
 image: guvanch/lab234-lab11-frontend:latest
 ports:
  - "8087:80"
    